name = "f1genz-sapo-r2-upload"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "f1genz-sapo-images"

[vars]
CDN_DOMAIN = "images-sapo.f1genz.dev"
